"""Renamed column project_ids to repos

Revision ID: 44e9454feb29
Revises: 94ba836bda04
Create Date: 2026-01-20 13:51:09.691111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '44e9454feb29'
down_revision: Union[str, Sequence[str], None] = '94ba836bda04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cde_configured_project', sa.Column('repos', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_column('cde_configured_project', 'project_ids')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cde_configured_project', sa.Column('project_ids', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('cde_configured_project', 'repos')
    # ### end Alembic commands ###
