"""Add user_id column to cde_configured_project

Revision ID: b75359337018
Revises: 44e9454feb29
Create Date: 2026-01-20 14:36:47.348845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b75359337018'
down_revision: Union[str, Sequence[str], None] = '44e9454feb29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cde_configured_project', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'cde_configured_project', 'adm_user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cde_configured_project', type_='foreignkey')
    op.drop_column('cde_configured_project', 'user_id')
    # ### end Alembic commands ###
